### ISSUE TITLE
Quick fix for RABBIT_MQ_DSN variable in messenger.yaml

### ISSUE THREAD

**Issue by dcantau** [the-fast-track/book-5.0-2#1]
**About 18.5 Going Async for Real**

Page 187, chapter 18.5 mentions a variable named `RABBITMQ_DSN`:

**config/packages/messenger.yaml**:

`async: '%env(RABBITMQ_DSN)%'`

For some reason, that variable has a different name on my computer:

`$ symfony var:export | sed "s/ /\n/g" | sort | grep -i RABBIT`
`RABBIT_MQ_DSN=amqp://:@127.0.0.1:32786`

So i just changed **config/packages/messenger.yaml** like this:

`async: '%env(RABBIT_MQ_DSN)%'`

Just added an underscore between `RABBIT` and `MQ`

Hope that helps!

++
Daniel

**Comment by fabpot** [comment]
Probably because you used `rabbit_mq` in your `docker-compose.yml` file instead of `rabbitmq`.
